codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: '70...100'
  status:
    project:
      default:
        informational: true
        target: 70%
        threshold: 5%
        paths:
          - 'src'

    patch:
      default:
        informational: true
        target: auto
        threshold: 10%
        paths:
          - 'src'

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: 'reach,diff,flags,files,footer'
  behavior: default
  require_changes: no
