version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:14.15

commands:
  resolve-dependencies:
    steps:
      - restore_cache:
          keys:
            - v1-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-yarn-packages-{{ .Branch }}-
            - v1-yarn-packages-

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn

      - save_cache:
          key: v1-yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

jobs:
  lint:
    executor: default

    steps:
      - run:
          name: Run Lint
          command: echo Lint

  test:
    executor: default

    steps:
      - run:
          name: Run Test
          command: echo Test

workflows:
  version: 2

  main:
    jobs:
      - lint

      - test:
          requires:
            - lint
