@startuml

title ドメインモデル図


package プレイヤー {
  object プレイヤー {
    プレイヤーID
    プレイヤー名
  }
}


package プレイ人数ルール {
  object プレイ人数ルール {
    プレイ人数ルールID
    プレイ人数ルール区分（4人/3人）
  }
}


package 参加プレイヤー一覧 {
  object 参加プレイヤー削除可能仕様 {
    成績保持プレイヤーID一覧
  }

  参加プレイヤー削除可能仕様 "1" --> "*" プレイヤー
  参加プレイヤー削除可能仕様 "1" --> "1" プレイヤー


  object 参加プレイヤー一覧更新イベント {
  }


  object 参加プレイヤー一覧 {
    参加プレイヤー一覧ID
    最小人数
    参加プレイヤーID一覧
  }

  参加プレイヤー一覧 "1" --> "3..*" プレイヤー
  参加プレイヤー一覧 "1" --> "1" 参加プレイヤー削除可能仕様
  参加プレイヤー一覧 "1" -l-> "1" 参加プレイヤー一覧更新イベント
}


package ウマ {
  object ウマ {
    ウマID
  }


  object 4人麻雀ウマ {
    4着から1着へ渡すポイント
    3着から2着へ渡すポイント
  }

  4人麻雀ウマ -u-|> ウマ


  object 3人麻雀ウマ {
    3着から1着へ渡すポイント
  }

  3人麻雀ウマ -u-|> ウマ
}


package オカ {
  object オカ {
    オカID
    持ち点
    返し点
  }
}


package 対局 {
  object プレイヤーポイント成績 {
    プレイヤーID
    ポイント
  }


  object 対局結果 {
    観戦プレイヤーID一覧
  }

  対局結果 "1" --> "*" プレイヤー
  対局結果 "1" *--> "*" プレイヤーポイント成績


  object 対局結果補正

  対局結果補正 "1" --> "1" 対局結果

  note top of 対局結果補正
  - 成績数が1つ足りない場合は補完する
  - 合計ポイントが0にならない場合は調整する
  - 成績保持プレイヤーを観戦プレイヤーから除外する
  end note


  object 対局結果仕様

  対局結果仕様 "1" --> "1" 対局結果

  note top of 対局結果仕様
  - 合計ポイントがゼロ
  - 同一ポイントが存在しない
  - 成績数がプレイ人数ルールと一致
  - 対局プレイヤーが参加プレイヤー一覧に含まれる
  - 対局プレイヤーが観戦プレイヤー一覧に含まれない
  - ウマ分の点数が加算されている
  - オカ分の点数が加算されている
  end note


  object 対局 {
    対局ID
  }

  対局 "1" *--> "3..4" プレイヤーポイント成績
  対局 "1" --> "1" 対局結果
  対局 "1" --> "1" 対局結果補正
  対局 "1" --> "1" 対局結果仕様
}


package 点数成績表 {
  object 点数成績表 {
    点数成績表ID
    対局ID一覧
  }

  点数成績表 "1" --> "*" 対局
}


package チップ成績表 {
  object プレイヤーチップ成績 {
    プレイヤーID
    チップ枚数
  }


  object チップ成績表仕様 {
    参加プレイヤーID一覧
  }

  チップ成績表仕様 "1" --> "*" プレイヤーチップ成績


  object チップ成績表 {
    チップ成績表ID
    チップ使用ルール区分（あり/なし）
  }

  チップ成績表 "1" *--> "3..*" プレイヤーチップ成績
  チップ成績表 "1" --> "1" チップ成績表仕様
}


package ポイントレート {
  object ポイントレート {
    ポイントレートID
    レート
  }
}


package チップレート {
  object チップレート {
    チップレートID
    レート
  }
}


package ゲーム代 {
  object ゲーム代 {
    ゲーム代ID
    ゲーム代
    支払者区分（全員/トップ）
  }
}


package 場所 {
  object 場所 {
    場所ID
    場所名
  }
}


package 成績表 {
  object 成績表 {
    成績表ID
    タイトル
    ノート
    記録日
  }

  成績表 "1" -u-> "0..1" 場所


  object バインダー {
    成績表ID
    参加プレイヤー一覧ID
    点数成績表ID
    チップ成績表ID
    プレイ人数ルールID
    ウマID
    オカID
    ポイントレートID
    チップレートID
    ゲーム代ID
  }

  バインダー "1" -r-> "1" 成績表
  バインダー "1" --> "1" 参加プレイヤー一覧
  バインダー "1" --> "1" 点数成績表
  バインダー "1" --> "1" チップ成績表
  バインダー "1" --> "1" プレイ人数ルール
  バインダー "1" --> "1" ウマ
  バインダー "1" --> "1" オカ
  バインダー "1" --> "1" ポイントレート
  バインダー "1" --> "1" チップレート
  バインダー "1" --> "1" ゲーム代
}


package 精算 {
  object 最終成績 {
    順位
    合計ポイント
    チップ枚数
  }

  最終成績 "1" --> "1" ポイントレート
  最終成績 "1" --> "1" チップレート
  最終成績 "1" --> "1" ゲーム代


  object プレイヤー収支 {
    プレイヤーID
    収支金額
  }

  プレイヤー収支 "1" *--> "1" 最終成績


  object 精算成績集計

  精算成績集計 "1" --> "*" プレイヤー収支
  精算成績集計 "1" -u-> "1" 参加プレイヤー一覧
  精算成績集計 "1" -u-> "*" プレイヤーポイント成績
  精算成績集計 "1" -u-> "1" プレイヤーチップ成績
}


package レポート {
  object 集計対象条件 {
    プレイヤーID
    プレイ人数ルール区分（4人/3人）
    記録期間
  }


  object 集計対象仕様 {
  }

  集計対象仕様 "1" --> "1" 集計対象条件
  集計対象仕様 "1" -u-> "*" 成績表


  object 着順回数 {
    1着回数
    2着回数
    3着回数
    4着回数
  }


  object 着順成績 {
    プレイ人数ルール区分（4人/3人）
    平均着順
    トップ率
    連対率
    ラス回避率
  }

  着順成績 "1" *--> "1" 着順回数


  object ポイント成績 {
    合計ポイント
    平均ポイント
  }


  object チップ成績 {
    合計チップ枚数
    平均チップ枚数
  }


  object 収支成績 {
    合計収支
  }


  object プレイヤー成績 {
    プレイヤーID
    対局数
  }

  プレイヤー成績 "1" *--> "1" 着順成績
  プレイヤー成績 "1" *--> "1" ポイント成績
  プレイヤー成績 "1" *--> "1" チップ成績
  プレイヤー成績 "1" *--> "1" 収支成績


  object 成績集計

  成績集計 "1" --> "*" プレイヤー成績
  成績集計 "1" --> "1" 集計対象仕様
  成績集計 "1" -u-> "*" プレイヤーポイント成績
  成績集計 "1" -u-> "*" プレイヤーチップ成績
  成績集計 "1" -u-> "*" 精算成績集計
}


@enduml
